# Generated by Django 5.2.4 on 2026-03-03 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='register',
            name='gender',
        ),
    ]
