# Generated by Django 4.2.7 on 2026-04-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_shippingcompany_shipping_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='shipping_company',
        ),
        migrations.AlterField(
            model_name='shipping',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='ShippingCompany',
        ),
    ]
