# Generated by Django 4.2.7 on 2026-04-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_delete_user_remove_seller_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
